filter_options:
  square_root: false
  HOUSE: false
  UKF: true
  CUT4: false
  CUT6: false
  num_trials: 1

scenario_parameters:
  MJD_start: 59349.51137986922
  MJD_end: 59351.54470621643
  max_time_step: 180
  output_directory: out/out_ccdata

initial_orbtial_parameters:
  dim_state: 6
  initial_state_type: "MEE"
  initial_state: [-3669575.62359752, 1040418.51432516, 6705990.19621435, -5051.32766883, -4686.71761172, -2035.77367562]
  initial_covariance: 
    - [1.0e+6, 0, 0, 0, 0, 0]
    - [0, 1.0e+4, 0, 0, 0, 0]
    - [0, 0, 4.0e+4, 0, 0, 0]
    - [0, 0, 0, 0.01, 0, 0]
    - [0, 0, 0, 0, 0.25, 0]
    - [0, 0, 0, 0, 0, 0.04]
  initial_skewness: -1.6
  initial_kurtosis: 15
  process_noise_covariance: 
    - [0.25, 0, 0, 0, 0, 0]
    - [0, 0.25, 0, 0, 0, 0]
    - [0, 0, 0.25, 0, 0, 0]
    - [0, 0, 0, 0.0001, 0, 0]
    - [0, 0, 0, 0, 0.0001, 0]
    - [0, 0, 0, 0, 0, 0.0001]

measurement_parameters:
  meas_file: ccdata/meas_data_id_46984.csv
  ground_station: [-2730000, 3714000, 4394000, 0, 0, 0]
  dim_meas: 2
  measurement_std: [5, 5]
  measurement_skew: [0, 0]
  measurement_kurt: [3, 3]

propagator_filter_settings:
  earth_gravity_model_order: 100
  earth_gravity_model_degree: 100
  third_body_attraction: true
  third_body_sun: true
  third_body_moon: true
  solid_earth_tide: true
  ocean_tide_loading: true
  solar_radiation_pressure: true
  atmospheric_drag: true
  relativity_effect: true
  srpCoef: 1.23
  srpArea: 8.73
  dragCoef: 2.0
  dragArea: 4.091655
  satMass: 961.831

supporting_files:
  gravity_file: ./auxdata/GGM03S.txt
  ephemeris_file: ./auxdata/linux_p1550p2650.440
  ERP_file: ./auxdata/cod21587.erp